hexapod_control_gui:
  ros__parameters:
    color_topic: /camera/color/image_raw
    depth_topic: /camera/depth/image_rect_raw
    battery_topic: /power/battery_state
    odom_topic: /odom
    imu_topic: /imu/data_raw
    diagnostics_topic: /diagnostics
    force_topic: /force_sensor_voltage_millivolts

    cmd_vel_topic: /cmd_vel_teleop
    cmd_vel_type: auto
    estop_topic: /safety/e_stop
    mode_topic: /mode/operation
    rider_topic: /mode/rider_present
    gait_mode_topic: /gait_mode
    gait_mode_type: auto

    publish_rate_hz: 20.0
    max_vx: 0.25
    max_vy: 0.25
    max_wz: 0.9
