controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

leg_velocity_controller:
  ros__parameters:
    joints:
      - fl_rightdown
      - fr_rightdown
      - lm_rightdown
      - rm_rightdown
      - bl_rightdown
      - br_rightdown
    interface_name: velocity
